I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 26, in script call
    call script_intro_start from _call_script_intro_start
  File "game/dev/scriptIntro.rpy", line 121, in script call
    call day0_main from _call_day0_main
  File "game/dev/day0/day0.rpy", line 390, in script
    show sayori 1b at t11 zorder 2 with leftin
Exception: Parameter 'new_widget' is not known by ATL Transform.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 26, in script call
    call script_intro_start from _call_script_intro_start
  File "game/dev/scriptIntro.rpy", line 121, in script call
    call day0_main from _call_day0_main
  File "game/dev/day0/day0.rpy", line 390, in script
    show sayori 1b at t11 zorder 2 with leftin
  File "C:\Users\Iride\Desktop\renpy-6.99.12.4-sdk\renpy\ast.py", line 1275, in execute
    renpy.exports.with_statement(trans, paired)
  File "C:\Users\Iride\Desktop\renpy-6.99.12.4-sdk\renpy\exports.py", line 1381, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\Iride\Desktop\renpy-6.99.12.4-sdk\renpy\display\core.py", line 2096, in do_with
    clear=clear)
  File "C:\Users\Iride\Desktop\renpy-6.99.12.4-sdk\renpy\display\core.py", line 2526, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\Iride\Desktop\renpy-6.99.12.4-sdk\renpy\display\core.py", line 2746, in interact_core
    new_widget=layers_root)
  File "C:\Users\Iride\Desktop\renpy-6.99.12.4-sdk\renpy\atl.py", line 413, in __call__
    raise Exception('Parameter %r is not known by ATL Transform.' % k)
Exception: Parameter 'new_widget' is not known by ATL Transform.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
DDLC 365 Day Zero DEMO 0.1.0
