I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 26, in script call
    call script_intro_start from _call_script_intro_start
  File "game/dev/scriptIntro.rpy", line 18, in script
    q "Welcome, Red Death."
KeyError: u'unknown_name'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 26, in script call
    call script_intro_start from _call_script_intro_start
  File "game/dev/scriptIntro.rpy", line 18, in script
    q "Welcome, Red Death."
  File "C:\Users\Iride\Desktop\renpy-6.99.12.4-sdk\renpy\ast.py", line 613, in execute
    renpy.exports.say(who, what, interact=self.interact)
  File "C:\Users\Iride\Desktop\renpy-6.99.12.4-sdk\renpy\exports.py", line 1147, in say
    who(what, interact=interact)
  File "C:\Users\Iride\Desktop\renpy-6.99.12.4-sdk\renpy\character.py", line 855, in __call__
    who = who_pattern.replace("[who]", sub(who))
  File "C:\Users\Iride\Desktop\renpy-6.99.12.4-sdk\renpy\character.py", line 850, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\Iride\Desktop\renpy-6.99.12.4-sdk\renpy\substitutions.py", line 232, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 605, in get_value
KeyError: u'unknown_name'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
DDLC 365 Day Zero DEMO 0.1.0
